import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { TRPCReactProvider } from '@/trpc/client'
import { Toaster } from '@/components/ui/sonner'
import { ThemeProvider } from 'next-themes'
import { APP_NAME } from './constants'
import { ClerkProvider } from '@clerk/nextjs'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: APP_NAME,
	description: 'Generated by Lummie',
	icons: {
		icon: [
			{
				url: '/logo.svg',
				media: '(prefers-color-scheme: light)',
			},
			{
				url: '/logo-l.svg',
				media: '(prefers-color-scheme: dark)',
			},
		],
	},
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<ClerkProvider
			appearance={{
				variables: {
					colorPrimary: '',
				},
			}}
		>
			<TRPCReactProvider>
				<html lang='en' suppressHydrationWarning>
					<body
						className={`${geistSans.variable} ${geistMono.variable} antialiased`}
					>
						<ThemeProvider
							attribute='class'
							defaultTheme='system'
							enableSystem
							disableTransitionOnChange
						>
							<Toaster />
							{children}
						</ThemeProvider>
					</body>
				</html>
			</TRPCReactProvider>
		</ClerkProvider>
	)
}
