import { APP_DESCRIPTION, APP_NAME, APP_URL } from '@/app/constants'
import { Metadata } from 'next'

export const metadata: Metadata = {
  metadataBase: new URL(APP_URL),

  title: 'Privacy',
  description: APP_DESCRIPTION,

  openGraph: {
    title: APP_NAME,
    description: APP_DESCRIPTION,
    url: APP_URL,
    siteName: APP_NAME,
    images: [
      {
        url: '/og-image.png',
        width: 1200,
        height: 630,
        alt: `Preview image for ${APP_NAME}`,
      },
    ],
    locale: 'en_US',
    type: 'website',
  },

  twitter: {
    card: 'summary_large_image',
    title: APP_NAME,
    description: APP_DESCRIPTION,
    images: ['/og-image.png'],
  },
}

export default function PrivacyPolicyPage() {
  return (
    <div className="bg-background text-foreground antialiased">
      <div className="container mx-auto max-w-4xl px-4 pt-24 pb-20 sm:pt-32 sm:pb-28 lg:pt-40 lg:pb-36">
        <header className="text-center">
          <h1 className="text-foreground text-4xl font-extrabold tracking-tight sm:text-5xl">
            Privacy Policy
          </h1>
          <p className="text-muted-foreground mt-4">
            Effective Date: August 29, 2025
          </p>
        </header>

        <main className="prose prose-neutral dark:prose-invert prose-lg prose-headings:font-bold prose-headings:text-foreground prose-a:text-primary hover:prose-a:text-primary/80 mt-16 max-w-none">
          <p>
            This Privacy Policy (&quot;Policy&quot;) governs the manner in which
            lummie.dev (&quot;Company,&quot; &quot;we,&quot; &quot;us,&quot; or
            &quot;our&quot;) collects, uses, maintains, and discloses
            information collected from users (&quot;User,&quot; &quot;you,&quot;
            or &quot;your&quot;) of the lummie.dev platform and any related
            services (collectively, the &quot;Services&quot;). Your access to
            and use of the Services is contingent upon your acceptance of and
            compliance with this Policy.
          </p>

          <h2>1. Information We Collect</h2>
          <p>
            We may collect information from and about you in various ways,
            including but not limited to, the following categories:
          </p>
          <ul>
            <li>
              <strong>Personally Identifiable Information (PII):</strong> This
              includes any information that can be used to identify you as an
              individual, which you voluntarily provide to us upon registration
              or during your use of the Services. This may include, but is not
              limited to, your name and email address.
            </li>
            <li>
              <strong>Service Data:</strong> We collect and store the natural
              language prompts you submit and the resulting source code
              generated by our Services. This data is integral to the core
              functionality of our platform and is utilized for the continuous
              improvement of our artificial intelligence models and service
              offerings.
            </li>
            <li>
              <strong>Usage Data:</strong> We automatically collect certain
              information when you access and use the Services. This information
              may include your Internet Protocol (IP) address, browser type and
              version, operating system, access times, and the pages you have
              viewed directly before and after accessing the Site.
            </li>
          </ul>

          <h2>2. Use of Your Information</h2>
          <p>
            We use the information we collect for various business purposes,
            including to:
          </p>
          <ul>
            <li>
              Create and manage your user account and to facilitate the
              provision of our Services.
            </li>
            <li>
              Generate, build, and deliver the application codebase you request.
            </li>
            <li>
              Monitor and analyze usage and trends to improve the functionality
              and user experience of the Services.
            </li>
            <li>
              Communicate with you regarding your account or updates to our
              Services.
            </li>
            <li>Respond to your inquiries and provide customer support.</li>
            <li>
              Prevent fraudulent activity and ensure the security of our
              Services.
            </li>
          </ul>

          <h2>3. Disclosure of Your Information</h2>
          <p>
            We do not sell, trade, or rent your PII to others. We may share
            information we have collected about you in certain situations, as
            follows:
          </p>
          <ul>
            <li>
              <strong>By Law or to Protect Rights:</strong> We may disclose your
              information if we believe in good faith that such disclosure is
              necessary to respond to legal process, investigate potential
              violations of our policies, or protect the rights, property, and
              safety of others, as required or permitted by any applicable law,
              rule, or regulation.
            </li>
            <li>
              <strong>Third-Party Service Providers:</strong> We may share your
              information with third-party vendors, consultants, and other
              service providers who perform services for us or on our behalf,
              such as cloud hosting, data analysis, and AI model provisioning,
              and who are contractually obligated to maintain the
              confidentiality of your information.
            </li>
            <li>
              <strong>Business Transfers:</strong> In connection with any
              merger, sale of company assets, financing, or acquisition of all
              or a portion of our business by another company, your information
              may be transferred as part of the transaction.
            </li>
          </ul>

          <h2>4. Security of Your Information</h2>
          <p>
            We employ administrative, technical, and physical security measures
            designed to protect your personal information. However, you
            acknowledge that no method of transmission over the Internet or
            method of electronic storage is 100% secure. While we strive to use
            commercially acceptable means to protect your information, we cannot
            guarantee its absolute security.
          </p>

          <h2>5. Policy for Children</h2>
          <p>
            Our Services are not directed to individuals under the age of 13. We
            do not knowingly collect personal information from children under
            13. If we become aware that a child under 13 has provided us with
            personal information, we will take steps to delete such information
            from our files.
          </p>

          <h2>6. Changes to This Privacy Policy</h2>
          <p>
            We reserve the right, at our sole discretion, to modify or replace
            this Policy at any time. We will alert you about any changes by
            updating the &quot;Effective Date&quot; of this Policy. Your
            continued use of the Services following the posting of any changes
            to this Policy constitutes acceptance of those changes.
          </p>

          <h2>7. Contact Us</h2>
          <p>
            Should you have any questions or comments regarding this Privacy
            Policy, please do not hesitate to contact us at:
            <br />
            <a href="mailto:privacy@lummie.dev">privacy@lummie.dev</a>
          </p>
        </main>
      </div>
    </div>
  )
}
