import { APP_DESCRIPTION, APP_NAME, APP_URL } from '@/app/constants'
import { Metadata } from 'next'

export const metadata: Metadata = {
  metadataBase: new URL(APP_URL),

  title: 'Privacy',
  description: APP_DESCRIPTION,

  openGraph: {
    title: APP_NAME,
    description: APP_DESCRIPTION,
    url: APP_URL,
    siteName: APP_NAME,
    images: [
      {
        url: '/og-image.png',
        width: 1200,
        height: 630,
        alt: `Preview image for ${APP_NAME}`,
      },
    ],
    locale: 'en_US',
    type: 'website',
  },

  twitter: {
    card: 'summary_large_image',
    title: APP_NAME,
    description: APP_DESCRIPTION,
    images: ['/og-image.png'],
  },
}

export default function PrivacyPolicyPage() {
  return (
    <div className="bg-background text-foreground antialiased">
      <div className="container mx-auto max-w-4xl px-4 pt-24 pb-20 sm:pt-32 sm:pb-28 lg:pt-40 lg:pb-36">
        <header className="text-center">
          <h1 className="text-foreground text-4xl font-extrabold tracking-tight sm:text-5xl">
            Privacy Policy
          </h1>
          <p className="text-muted-foreground mt-4">
            Effective Date: October 2, 2025
          </p>
        </header>

        <main
          className="prose prose-neutral dark:prose-invert prose-lg prose-headings:font-bold prose-headings:text-foreground prose-a:text-primary hover:prose-a:text-primary/80 mt-16 max-w-none">
          <div className="privacy-policy-content">
            <p>This Privacy Policy ("Policy") governs the manner in which lummie.dev ("Company," "we," "us," or "our")
              collects, uses, maintains, and discloses information collected from users ("User," "you," or "your") of
              the lummie.dev platform and any related services (collectively, the "Services"). Your access to and use of
              the Services is contingent upon your acceptance of and compliance with this Policy.</p>

            <h2 className='text-bold text-2xl mt-2 mb-2'>1. Information We Collect</h2>
            <p>We may collect information from and about you in various ways, including but not limited to, the
              following categories:</p>
            <ul>
              <li><strong>Personally Identifiable Information (PII):</strong> Information that can be used to identify
                you, which you voluntarily provide upon registration or during your use. This includes:
                <ul>
                  <li><strong>Contact Data:</strong> Your name and email address.</li>
                  <li><strong>Account Credentials:</strong> Encrypted password or authentication tokens from third-party
                    sign-in services (e.g., Google).
                  </li>
                </ul>
              </li>
              <li><strong>Service Data (Prompts and Generated Code):</strong> We collect and store the natural language
                prompts you submit and the resulting source code generated by our Services. This data is integral to the
                core functionality of our platform.
              </li>
              <li><strong>Payment Data:</strong> When you purchase a subscription, we do <strong>not</strong> directly
                store your full credit card number. We collect limited payment data (e.g., last four digits of the card,
                expiry date) and rely on a <strong>PCI-DSS compliant third-party payment processor</strong> to handle
                the transaction.
              </li>
              <li><strong>Usage Data:</strong> We automatically collect certain information when you access and use the
                Services. This includes your <strong>Internet Protocol (IP) address</strong>, browser type, operating
                system, access times, pages viewed, and other diagnostic data.
              </li>
            </ul>

            <h2 className='text-bold text-2xl mt-2 mb-2'>2. Use of Your Information and Legal Basis for Processing (GDPR)</h2>
            <p>We use the information we collect for various purposes, supported by the following legal bases required
              by GDPR:</p>
            <table>
              <thead>
              <tr>
                <th>Purpose of Use</th>
                <th>Legal Basis (GDPR)</th>
                <th>Data Type</th>
              </tr>
              </thead>
              <tbody>
              <tr>
                <td><strong>Provision of Services</strong> (Account creation, code generation)</td>
                <td><strong>Performance of a contract</strong></td>
                <td>PII, Service Data</td>
              </tr>
              <tr>
                <td><strong>Service Improvement</strong> (Monitoring, analyzing trends)</td>
                <td><strong>Legitimate interest</strong> (if data is anonymized)</td>
                <td>Usage Data, Service Data</td>
              </tr>
              <tr>
                <td><strong>Marketing and Communication</strong> (Service updates)</td>
                <td><strong>Consent</strong> or <strong>Legitimate interest</strong></td>
                <td>PII</td>
              </tr>
              <tr>
                <td><strong>Security and Fraud Prevention</strong></td>
                <td><strong>Legitimate interest</strong></td>
                <td>PII, Usage Data</td>
              </tr>
              <tr>
                <td><strong>Payment Processing</strong></td>
                <td><strong>Performance of a contract</strong></td>
                <td>Payment Data</td>
              </tr>
              </tbody>
            </table>

            <h2 className='text-bold text-2xl mt-2 mb-2'>3. Service Data (Prompts and Code) Clarification</h2>
            <p>We utilize Service Data (prompts and generated code) for the continuous improvement of our artificial
              intelligence models and service offerings.</p>
            <p><strong>Important Note:</strong> We implement measures to prevent the unintentional inclusion of
              Personally Identifiable Information (PII) within our AI model training data. <strong>However, you are
                responsible for ensuring that you do not input sensitive personal, proprietary, or confidential
                information into the service prompts.</strong> By submitting prompts, you acknowledge and agree that
              this Service Data will be used for model training and service enhancement, and you waive any
              confidentiality claims regarding the input data.</p>

            <h2 className='text-bold text-2xl mt-2 mb-2'>4. Disclosure and International Transfer of Your Information</h2>
            <p>We do not sell, trade, or rent your PII to others. We may share information we have collected about you
              as follows:</p>
            <ul>
              <li><strong>Third-Party Service Providers:</strong> We share information with vendors who perform services
                on our behalf (e.g., cloud hosting, payment processing, data analysis, AI model provisioning). These
                providers are contractually obligated to maintain the confidentiality and security of your information.
              </li>
              <li><strong>Business Transfers:</strong> Your information may be transferred as part of a merger, sale of
                assets, or acquisition.
              </li>
              <li><strong>Legal Requirements:</strong> We may disclose your information if required by law, regulation,
                or a legal process (e.g., court order or subpoena).
              </li>
            </ul>
            <h3>International Data Transfers</h3>
            <p>Since we operate globally, your information may be transferred to, and stored in, countries outside your
              state, province, or country of residence, including the <strong>United States</strong>, where data
              protection laws may differ from those in your jurisdiction. We take all steps reasonably necessary to
              ensure that your data is treated securely and in accordance with this Policy, utilizing mechanisms such
              as <strong>Standard Contractual Clauses (SCCs)</strong> where required by GDPR.</p>

            <h2 className='text-bold text-2xl mt-2 mb-2'>5. Data Security and Retention</h2>
            <p><strong>Security:</strong> We employ administrative, technical, and physical security measures to protect
              your personal information. While we strive to use commercially acceptable means to protect your
              data, <strong>no method of transmission over the Internet is 100% secure.</strong></p>
            <p><strong>Data Retention:</strong> We retain your Personal Data only for as long as is necessary for the
              purposes set out in this Policy. Generally, we will retain your PII <strong>for the duration your account
                is active</strong> and for a reasonable period thereafter (e.g., 90 days) to allow for account recovery
              or internal backup purposes, unless a longer retention period is required or permitted by law.</p>

            <h2 className='text-bold text-2xl mt-2 mb-2'>6. Your Data Protection Rights (GDPR and Global Users)</h2>
            <p>Depending on your location, you may have the following rights regarding your Personal Data:</p>
            <ul>
              <li><strong>Right of Access (Right to Know):</strong> The right to request copies of your Personal Data.
              </li>
              <li><strong>Right to Rectification:</strong> The right to request that we correct any information you
                believe is inaccurate or incomplete.
              </li>
              <li><strong>Right to Erasure (Right to be Forgotten):</strong> The right to request that we delete your
                Personal Data, under certain conditions.
              </li>
              <li><strong>Right to Restrict Processing:</strong> The right to request that we limit the way we use your
                Personal Data.
              </li>
              <li><strong>Right to Data Portability:</strong> The right to request that we transfer the data we have
                collected to another organization, or directly to you, under certain conditions.
              </li>
              <li><strong>Right to Object:</strong> The right to object to our processing of your Personal Data.</li>
            </ul>
            <p>To exercise any of these rights, please contact us using the details below. We will respond to your
              request within the timeframe required by applicable law.</p>

            <h2 className='text-bold text-2xl mt-2 mb-2'>7. Policy for Children</h2>
            <p>Our Services are not directed to individuals under the age of 13. We do not knowingly collect personal
              information from children under 13.</p>

            <h2 className='text-bold text-2xl mt-2 mb-2'>8. Changes to This Privacy Policy</h2>
            <p>We reserve the right, at our sole discretion, to modify or replace this Policy at any time. We will alert
              you about any changes by updating the <strong>"Effective Date"</strong> of this Policy and notifying you
              via email or a prominent notice on the Services prior to the change becoming effective.</p>

            <h2 className='text-bold text-2xl mt-2 mb-2'>9. Contact Us</h2>
            <p>Should you have any questions or comments regarding this Privacy Policy, please do not hesitate to
              contact us at:</p>
            <p><strong>Email:</strong> privacy@lummie.dev</p>
          </div>
        </main>
      </div>
    </div>
  )
}
